# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    #upscale regularise l'image si la taille requis manque il égalise par exemple largeur 160
    #il transforme en 200 taille demandée
    driver: "gd"
    filter_sets:
        image_grand:
            filters:

                # use and setup the "upscale" filter
                thumbnail:

                    # input 1980x1280px -> output 3960x2560px
                    size: [300, 300]
                    mode: outbound
                    allow_upscale: true


        # name our second filter set "my_by_up_scale_filter"
        image_petit:
            filters:

                # use and setup the "upscale" filter
                thumbnail:

                    # input 1980x1280px -> output 3960x2560px
                    size: [400, 200]
                    mode: outbound
                    allow_upscale: true



