security:
    encoders:
        App\Entity\User:
            algorithm: auto
        mon_encoder:
            algorithm: bcrypt
            cost: 13

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    #Le provider va nous permettre de sauvegarder l'email dans la session comme precisé dans property
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:  
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
        #autorisation des connexions anonymes
            anonymous: true
        #gagner en terme de performance
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                #Sécurité pour la déconnexion
                #POST
                #csrf_parameter:       csrf_token
 #Ceci est tres important à préciser
                csrf_token_generator: Symfony\Component\Security\Csrf\CsrfTokenManagerInterface
                #POST
                #csrf_token_id:        logout
                # where to redirect after logout
                target: app_login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/account, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
        #Pour plus de facilité
        - { path: ^/login$, roles: IS_ANONYMOUS }
        - { path: ^/register$, roles: IS_ANONYMOUS }
        - { path: ^/reset-password, roles: IS_ANONYMOUS }
        - { path: ^/account/edit, roles: IS_AUTHENTICATED_FULLY }
        
        #- { path: ^/reset-password/check-email$, roles: IS_ANONYMOUS }
        #- { path: ^/, roles: ROLE_USER }

        #Gestion de plusieurrs role
    role_hierarchy:
        ROLE_PROF: [ROLE_DONNER_COURS,ROLE_DONNER_NOTE]
        ROLE_ETUDIANT: [ROLE_SUIVRE_COURS,ROLE_CONSULTER]
        #impersonalisation autorisation
        ROLE_USER: [ROLE_ALLOWED_TO_SWITCH]